Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using replicaPROGRAMA.Models;
using replicaPROGRAMA.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;

namespace replicaPROGRAMA.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ILogger<CarritoController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public CarritoController(ILogger<CarritoController> logger, ApplicationDbContext context,UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;
        }
        
       public IActionResult IndexUltimoProductoSesion()
        {
            var producto  = Util.SessionExtension.Get<Producto>(HttpContext.Session,"MiUltimoProducto");
            return View("UltimoProducto",producto);
        }

         public IActionResult Index()
        {
            var userIDSession = _userManager.GetUserName(User);
            if(userIDSession == null){
                ViewData["Message"] = "Por favor debe loguearse antes de agregar un producto";
                return RedirectToAction("Index","Catalogo");
            }
            var items = from o in _context.DataItemCarrito select o;
            items = items.Include(p => p.Producto).
                    Where(w => w.UserID.Equals(userIDSession) &&
                        w.Status.Equals("PENDIENTE"));
            var itemsCarrito = items.ToList();
            //Total a pagar
            var total = itemsCarrito.Sum(c => c.Cantidad * c.Precio);

            //Almacenar datos de la Compra
            dynamic model = new ExpandoObject();
            model.montoTotal = total;
            model.elementosCarrito = itemsCarrito;
            return View(model);
        }

        public async Task<IActionResult> Add(int? id){
            var userID = _userManager.GetUserName(User);
            if(userID == null){
                _logger.LogInformation("No existe usuario");
                ViewData["Message"] = "Por favor debe loguearse antes de agregar un producto";
                return RedirectToAction("Index","Catalogo");
            }else{
                var producto = await _context.DataProducto.FindAsync(id);
                Util.SessionExtension.Set<Producto>(HttpContext.Session,"MiUltimoProducto", producto);
                Proforma proforma = new Proforma();
                proforma.Producto = producto;
                proforma.Precio = producto.Price;
                proforma.Cantidad = 1;
                proforma.UserID = userID;
                _context.Add(proforma);
                await _context.SaveChangesAsync();
                ViewData["Message"] = "Se Agrego al carrito";
                _logger.LogInformation("Se agrego un producto al carrito");
                return RedirectToAction("Index","Catalogo");
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemCarrito = await _context.DataItemCarrito.FindAsync(id);
            _context.DataItemCarrito.Remove(itemCarrito);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemCarrito = await _context.DataItemCarrito.FindAsync(id);
            if (itemCarrito == null)
            {
                return NotFound();
            }
            return View(itemCarrito);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cantidad,Precio,UserID")] Proforma itemCarrito)
        {
            if (id != itemCarrito.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(itemCarrito);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.DataItemCarrito.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itemCarrito);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using replicaPROGRAMA.Models;
using Microsoft.AspNetCore.Identity;
using replicaPROGRAMA.Data;
using Microsoft.EntityFrameworkCore;

namespace replicaPROGRAMA.Controllers
{
    public class PagoController : Controller
    {
        private readonly ILogger<PagoController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public PagoController(ILogger<PagoController> logger, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Create(Decimal monto)
        {

            Pago pago = new Pago();
            pago.UserID = _userManager.GetUserName(User);
            pago.MontoTotal = monto;
            return View(pago);
        }

        [HttpPost]
        public IActionResult Pagar(Pago pago)
        {
            pago.PaymentDate = DateTime.UtcNow;
            _context.Add(pago);

            var itemsCarrito = from o in _context.DataItemCarrito select o;
            itemsCarrito = itemsCarrito.
                Include(p => p.Producto).
                Where(s => s.UserID.Equals(pago.UserID) && s.Status.Equals("PENDIENTE"));

            Pedido pedido = new Pedido();
            pedido.UserID = pago.UserID;
            pedido.Total = pago.MontoTotal;
            pedido.pago = pago;
            pedido.Status = "PENDIENTE";
            _context.Add(pedido);

            List<DetallePedido> itemsPedido = new List<DetallePedido>();
            foreach(var item in itemsCarrito.ToList()){
                DetallePedido detallePedido = new DetallePedido();
                detallePedido.pedido=pedido;
                detallePedido.Precio = item.Precio;
                detallePedido.Producto = item.Producto;
                detallePedido.Cantidad = item.Cantidad;
                itemsPedido.Add(detallePedido);
            }


            _context.AddRange(itemsPedido);

            foreach (Proforma p in itemsCarrito.ToList())
            {
                p.Status="PROCESADO";
            }

            _context.UpdateRange(itemsCarrito);

            _context.SaveChanges();

            ViewData["Message"] = "El pago se ha registrado y su pedido nro "+ pedido.ID +" esta en camino";
            return View("Create");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Carrito/Edit.cshtml
@model replicaPROGRAMA.Models.Proforma

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Proforma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Carrito" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserID" />
            <input type="hidden" asp-for="Precio" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carrito/Index.cshtml
@model dynamic;
@using System.Collections.Generic;

@{
    ViewData["Title"] = "Carrito";
    IEnumerable<replicaPROGRAMA.Models.Proforma> listItemsCarrito = new List<Proforma>();
    listItemsCarrito = @Model.elementosCarrito;
    Decimal montoTotal = @Model.montoTotal;
}

<h1>@ViewData["Title"]</h1>

<a class="btn btn-primary" asp-controller="Pago" 
        asp-action="Create" asp-route-monto="@montoTotal">Pagar</a><p>Total S/. @montoTotal</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Producto.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (Proforma item in Model.elementosCarrito) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Carrito/UltimoProducto.cshtml
@model replicaPROGRAMA.Models.Producto

@{
    ViewData["Title"] = "Ultimo Producto de la Sesion";
}

    <h1>>@ViewData["Title"]</h1>
    <div class="container">
            <div class="col-sm-4">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="card-img-actions">
                    <img class="img-responsive" width="96" height="150"
                      src="@Html.DisplayFor(model => model.ImageURL)"  />
                  </div>
                </div>
                <div class="card-body">
                  <h5 class="card-title">@Html.DisplayFor(model => model.Name)</h5>
                  <h5 class="card-title">@Html.DisplayFor(model => model.Price)</h5>
                  <a class="btn btn-primary" asp-action="Add" asp-route-id="@Model.Id">Add</a>
                </div>
              </div>
            </div>
    </div>